name: GitHub Help

trigger:
  branches:
    include:
      - main

parameters:
- name: azureServiceConnection
  type: string
  default: 'service-connection'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: MizuEna
    displayName: 'MizuEna Stage'
    jobs:
      - job: MizuEnaJob
        displayName: 'MizuEna Job'
        steps:
          - script: echo "MizuEna..."
            displayName: 'MizuEna Step'
  - stage: DeployKeyVault
    displayName: 'Deploy Key Vault Stage'
    jobs:
      - job: DeployKeyVaultJob
        displayName: 'Deploy Key Vault'
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: ${{ parameters.azureServiceConnection }}
              subscriptionId: 'bf1b5129-7317-4dff-b781-a1b1f3c49520'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'AZ-400'
              location: 'westeurope'
              templateLocation: 'Linked Artifact'
              csmFile: '../infrastructure/keyvault.bicep'
